angristan/nginx-autoinstall

- nginx-autoinstall.sh
Built tested on Debian8 with :
openssl 1.0.0t
openssl 1.1.0e
libressl 2.5.1
> Cloudflare tls resizing + LibreSSL dev 2.5.1

- nginx-autoinstall.sh
Changelog - 24 Mar 2017
*) Bugfix: nginx might hog CPU; the bug had appeared in 1.11.11.
Source: nginx.org
> Update nginx to 1.11.12

- nginx-autoinstall.sh
Changes with nginx 1.12.0                                        12 Apr 2017
*) 1.12.x stable branch.
> Update nginx to 1.12.0 - STABLE \o\

- README.md
- nginx-autoinstall.sh
https://github.com/FRiCKLE/ngx_cache_purge
from https://github.com/Angristan/nginx-autoinstall/issues/41#issuecomment-366427835
> Add ngx_cache_purge

- nginx-autoinstall.sh
Thanks for a great script! 🤓
Added support for nginx WebDAV 👍
Just thought I'd share.
- Tested and working on Debian GNU/Linux 9.8 (stretch)
> Nginx dav ext module

- nginx-autoinstall.sh
Added creation of /etc/nginx/conf.d directory. Ref #87
> Create /etc/nginx/conf.d directory

- nginx-autoinstall.sh
Add support for [ngx_http_sub_module](http://nginx.org/en/docs/http/ngx_http_sub_module.html)
> Add Module ngx_http_sub_module

- README.md
- nginx-autoinstall.sh
Tested and working on two Debian 10 servers. :+1:
> Add ModSecurity module

- README.md
- conf/README.md
- nginx-autoinstall.sh
> Add HTTP/3 support

- README.md
- nginx-autoinstall.sh
Added lua-nginx-module from Firegarden: https://github.com/angristan/nginx-autoinstall/issues/65
Tested and working on two Debian 10 servers. :+1:
> Add Lua nginx module

- README.md
- nginx-autoinstall.sh
> Add option to install nginx-ultimate-bad-bot-blocker

- README.md
- conf/README.md
- nginx-autoinstall.sh
Tested and working on two Debian 10 severs. :+1:
> Testcookie nginx module

- README.md
- nginx-autoinstall.sh
> Add Dynamic TLS Records support

- README.md
- nginx-autoinstall.sh
Hey there,
I bumped the version of NGINX and OpenSSL.
I also bumped the version of some modules,
there are some other modules I haven't bumped because I ain't sure if they are safe to update.
> Bump version of NGINX, OpenSSL, Lua NGINX and NGINX Dev Kit and change the repo for the Brotli module

- nginx-autoinstall.sh
When I did my test on the script for the Brotli repo change, I did remove a line that wasn't necessary anymore, however, when I worked the changes back on the original script, I forgot to remove this said line.
My bad for the mistake.
> Fixed a small mistake for the Brotli repo change

- nginx-autoinstall.sh
> Add TLS Dynamic Record Resizing for nginx stable

- nginx-autoinstall.sh
Less download size, we need only the HEAD code
Example size with the quiche repository:
```
264M	quiche
143M	quiche-depth-1
```
> Add --depth to git clone command

- nginx-autoinstall.sh
Hey,
This tiny PR will fix : 
- 1 typo in `nginx-autoinstall.sh`
Ciao! :robot:
> docs: fix typo in nginx-autoinstall.sh

- nginx-autoinstall.sh
Added RTMP module.
Closing #163
> Add RTMP module

- README.md
- nginx-autoinstall.sh
Added ngx http substitutions filter module.
Closing  #130
> Add ngx_http_substitutions_filter_module

- README.md
- nginx-autoinstall.sh
Add Cloudflare HPACK support.
Closes #165
Not sure if in the right place, but i think so 🤔
*Not tested
> Add Cloudflare HPACK

- nginx-autoinstall.sh
Remove duplicate "RTMP=${RTMP:-n}".
> Remove duplicate RTMP

- .github/workflows/docker/wrapper.sh
- README.md
- conf/GeoIP.conf
- nginx-autoinstall.sh
- Added license authentication to download GeoLite2.
- Added ASN database
- added crontab for `geoipupdate`
- This adds `GeoIP.conf` to `/usr/local/etc with credentials`
- Added change `main` to `main contrib` in `/etc/apt/sources.list` (to install geoipupdate from APT)
- Added credentials to headless install
- Updated README.md and wrapper.sh
Installed with:
```
HEADLESS=y \
NGINX_VER=MAINLINE \
PAGESPEED=y \
BROTLI=y \
HEADERMOD=y \
GEOIP=y \
GEOIP2_ACCOUNT_ID=YOUR_ACCOUNT_ID_HERE \
GEOIP2_LICENSE_KEY=YOUR_LICENSE_KEY_HERE \
FANCYINDEX=y \
CACHEPURGE=y \
SUBFILTER=y \
LUA=y \
WEBDAV=y \
VTS=y \
RTMP=y \
TESTCOOKIE=y \
REDIS2=y \
HTTPREDIS=y \
SRCACHE=y \
SETMISC=y \
NGXECHO=y \
./nginx-autoinstall.sh 2>&1 | tee nginx-installer.log
```
Install log (license key omitted): …
> Geoip patch
